name: Run DLT Pipeline

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  run-dlt-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: uv sync

      - name: Run DLT Pipeline
        run: uv run dlt_pipe.py
